---

- include: prereqs.yml
- include: jdk.yml

- include: fw-{{ PROVIDER }}.yml
- include: networking.yml
- include: selinux.yml


- name: Edge AIO Install and Config
  hosts: all
  become: yes
  become_method: sudo
  vars:
    # IP1: 10.132.0.3
    # PROVIDER: vb|gce




  tasks:
  - template: src=conf/aio.cfg.j2 dest=/opt/aio.cfg

